export default {
  bike: require("assets/images/guide/bike.png"),
  earth: require("assets/images/guide/earth.png"),
  restaurant: require("assets/images/guide/restaurant.png"),
  homeBanner: require("assets/images/Home/home1.png"),
  news1: require("assets/images/Home/news1.png"),
  news2: require("assets/images/Home/news2.png"),
  cat_automotive: require("assets/images/categories/automotive.png"),
  cat_baby: require("assets/images/categories/baby.png"),
  cat_food: require("assets/images/categories/food.png"),
  cat_sports: require("assets/images/categories/sports.png"),
  cat_travel: require("assets/images/categories/travel.png"),
  cat_music: require("assets/images/categories/music.png"),
  cat_fitness: require("assets/images/categories/fitness.png"),
  cat_money: require("assets/images/categories/money.png"),
  cat_health: require("assets/images/categories/health.png"),
  cat_software: require("assets/images/categories/software.png"),
  post1: require("assets/images/Post/1.png"),
  post2: require("assets/images/Post/2.png"),
  post3: require("assets/images/Post/3.png"),
  useravatar1: require("assets/images/User/1.png"),
  useravatar2: require("assets/images/User/2.png"),
  useravatar3: require("assets/images/User/3.png"),
  postImg: require("assets/images/Post/postImg.png"),
};
