import { StyleSheet } from "react-native";

import { Layout, Colors, Font } from "style";

export default StyleSheet.create({
  container: {
    marginVertical: 12,
  },
  container_noImg: {
    marginVertical: 12,
    backgroundColor: Colors.white,
    height: 170,
    borderWidth: 1,
    borderRadius: 15,
    borderColor: "#E2E6F1",
  },
  image: {
    width: "100%",
    borderWidth: 1,
    borderRadius: 15,
    borderColor: "transparent",
    height: 250,
  },
  recommend: {
    position: "absolute",
    width: 70,
    height: 30,
    top: 25,
    left: 0,
    backgroundColor: "#1D2234",
    opacity: 0.6,
    borderColor: "transparent",
    borderWidth: 1,
    borderTopRightRadius: 15,
    borderBottomRightRadius: 15,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  recommend_icon: {
    position: "absolute",
    top: 32,
    left: 11.3,
  },
  recommend_num: {
    position: "absolute",
    top: 32,
    left: 31,
    color: Colors.white,
    fontFamily: Font.FontFamily.Poppin,
    fontWeight: "400",
    fontSize: Font.FontSize.Secondary,
  },
  save: {
    position: "absolute",
    width: 40,
    height: 40,
    top: 20,
    right: 20,
    backgroundColor: "#1D2234",
    opacity: 0.6,
    borderColor: "transparent",
    borderWidth: 1,
    borderRadius: 50,
  },
  save_noImg: {
    position: "absolute",
    width: 40,
    height: 40,
    top: 20,
    right: 20,
    backgroundColor: "#ED5466",
    opacity: 0.15,
    borderColor: "transparent",
    borderWidth: 1,
    borderRadius: 50,
  },
  heart_icon: {
    position: "absolute",
    top: 32,
    right: 29.5,
  },
  post_info: {
    position: "absolute",
    left: "5%",
    top: "60%",
    width: "90%",
    paddingVertical: 15,
    paddingHorizontal: 16,
    backgroundColor: Colors.white,
    borderRadius: 12,
  },
  post_info_noImg: {
    position: "absolute",
    left: 0,
    top: "45%",
    width: "100%",
    paddingVertical: 15,
    paddingHorizontal: 16,
    backgroundColor: Colors.white,
  },
  title: {
    position: "relative",
    fontFamily: Font.FontFamily.Poppin,
    fontWeight: "500",
    fontSize: Font.FontSize.Primary,
    lineHeight: Font.FontLineHeight.Secondary,
    color: Colors.darkGrey,
    width: "100%",
    marginBottom: 8,
  },
  subcategory: {
    paddingVertical: 5,
    paddingHorizontal: 12,
    fontFamily: Font.FontFamily.Poppin,
    fontWeight: "400",
    fontSize: Font.FontSize.Tertiary,
    lineHeight: 15,
    color: Colors.green,
    backgroundColor: Colors.lightGreen,
    borderRadius: 30,
    width: "auto",
    alignSelf: "flex-start",
  },
  publish: {
    alignSelf: "flex-end",
    display: "flex",
    flexDirection: "row",
    textAlignVertical: "center",
  },
  publishDate: {
    fontFamily: Font.FontFamily.Poppin,
    fontWeight: "400",
    fontSize: Font.FontSize.Secondary,
    lineHeight: 18,
    color: "#5E667C",
  },
});
